apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 3 # Yatayda ölçeklenmeyi doğrulamak için 3 replica
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: "postgres://app:app@postgres:5432/inference_db"
            - name: INFERENCE_URL
              value: "http://inference:8001"
            - name: KAFKA_BROKERS
              value: "kafka:9092"
            - name: REDIS_ADDR
              value: "redis:6379"
          volumeMounts:
            - name: uploads-storage
              mountPath: /app/uploads
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: uploads-pvc